language: objective-c
os: osx
osx_image: xcode8.3

cache: cocoapods
podfile: TXBrowserDemo/Podfile

env:
  global:
    - XCODE_WORKSPACE=TXBrowserDemo/TXBrowserDemo.xcworkspace
  matrix:
    - SCHEME="TXBrowserDemo"

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod install --project-directory=TXBrowserDemo

script:
  - set -o pipefail
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - pod lib lint --no-clean
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sleep 5
