language: objective-c
os: osx
osx_image: xcode8.3

env:
  global:
    - XCODE_WORKSPACE=TXBrowserDemo/TXBrowserDemo.xcworkspace
  matrix:
    - SCHEME="TXBrowserDemo"

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - xcodebuild -scheme "$SCHEME" -workspace "$XCODE_WORKSPACE" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sleep 3
